#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Console\Input\ArgvInput;

require __DIR__.'/vendor/autoload.php';
exit((require __DIR__.'/bootstrap/app.php')->handleCommand(new ArgvInput()));
