version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /starters/web
      - /starters/web-vanilla
      - /starters/backend-node
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: composer
    directory: /starters/backend-php
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /starters/kotlin-android
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /starters/flutter
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /starters/backend-php/docker
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
