// SPDX-FileCopyrightText: 2026 Zendrhax LLC
// SPDX-License-Identifier: MPL-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { SqliteStore } from '../src/sqlite.js';
import { issueToken } from '../src/application.js';
import { createApiServer } from '../src/server.js';

async function fixture(){ const store=new SqliteStore(':memory:'); const owner=issueToken(store,'owner',['tasks:read','tasks:write']); const other=issueToken(store,'other',['tasks:read','tasks:write']); const server=createApiServer(store); server.listen(0,'127.0.0.1'); await once(server,'listening'); const address=server.address(); if(!address||typeof address==='string') throw new Error(); const call=(path:string,init:RequestInit={})=>fetch(`http://127.0.0.1:${address.port}${path}`,{...init,headers:{Authorization:`Bearer ${owner}`,...init.headers}}); return {store,server,owner,other,call}; }
test('health, authentication, CRUD, concurrency and revocation follow the contract',async()=>{ const f=await fixture(); try { const port=(f.server.address() as {port:number}).port; assert.deepEqual(await (await fetch(`http://127.0.0.1:${port}/api/health`)).json(),{status:'ok',scope:'liveness'}); assert.equal((await fetch(`http://127.0.0.1:${port}/api/v1/tasks`)).status,401); const created=await f.call('/api/v1/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'  Tarea 🙂  '})}); assert.equal(created.status,201); const task=(await created.json() as {data:{id:string,title:string}}).data; assert.equal(task.title,'Tarea 🙂'); assert.equal((await f.call(`/api/v1/tasks/${task.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Done',completed:true,version:1})})).status,200); assert.equal((await f.call(`/api/v1/tasks/${task.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Stale',completed:false,version:1})})).status,409); assert.equal((await f.call('/api/v1/auth/token',{method:'DELETE'})).status,204); assert.equal((await f.call('/api/v1/tasks')).status,401); } finally { f.server.close(); f.store.close(); } });
test('ownership and bounded validation are enforced',async()=>{ const f=await fixture(); try { const response=await f.call('/api/v1/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Private'})}); const id=(await response.json() as {data:{id:string}}).data.id; const port=(f.server.address() as {port:number}).port; assert.equal((await fetch(`http://127.0.0.1:${port}/api/v1/tasks/${id}`,{headers:{Authorization:`Bearer ${f.other}`}})).status,404); assert.equal((await f.call('/api/v1/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'x',unknown:true})})).status,422); assert.equal((await f.call('/api/v1/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'\ud800'})})).status,422); assert.equal((await f.call('/api/v1/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:new Uint8Array([123,34,116,105,116,108,101,34,58,34,255,34,125])})).status,400); assert.equal((await f.call('/api/v1/tasks?limit=101')).status,422); assert.equal((await f.call('/api/v1/tasks?limit=1&limit=2')).status,422); } finally { f.server.close(); f.store.close(); } });
test('localization, permissions, media rules, method metadata and persistent limiting are enforced',async()=>{ const f=await fixture(); try { const port=(f.server.address() as {port:number}).port; const readOnly=issueToken(f.store,'reader',['tasks:read']); const denied=await fetch(`http://127.0.0.1:${port}/api/v1/tasks`,{method:'POST',headers:{Authorization:`Bearer ${readOnly}`,'Content-Type':'application/json','Accept-Language':'es-419'},body:JSON.stringify({title:'No'})}); assert.equal(denied.status,403); assert.equal(denied.headers.get('content-language'),'es-419'); assert.equal((await denied.json() as {error:{message:string}}).error.message,'La operación no está permitida.'); assert.equal((await f.call('/api/v1/tasks',{method:'POST',body:JSON.stringify({title:'No type'})})).status,415); const method=await f.call('/api/v1/tasks',{method:'PATCH'}); assert.equal(method.status,405); assert.equal(method.headers.get('allow'),'GET, POST'); const window=Math.floor(Date.now()/60000); for(let index=0;index<120;index++) assert.equal(f.store.consume('separate-limit-key',window,120),true); assert.equal(f.store.consume('separate-limit-key',window,120),false); } finally { f.server.close(); f.store.close(); } });
test('language quality values select the strongest supported preference',async()=>{ const f=await fixture(); try { const port=(f.server.address() as {port:number}).port; const response=await fetch(`http://127.0.0.1:${port}/api/v1/tasks`,{headers:{'Accept-Language':'en-US;q=0.2, es-419;q=0.9'}}); assert.equal(response.status,401); assert.equal(response.headers.get('content-language'),'es-419'); assert.equal((await response.json() as {error:{message:string}}).error.message,'Se requiere autenticación.'); } finally { f.server.close(); f.store.close(); } });
test('CORS allows only configured origins and bounded preflights',async()=>{ const store=new SqliteStore(':memory:'); const server=createApiServer(store,['http://127.0.0.1:5173']); server.listen(0,'127.0.0.1'); await once(server,'listening'); try { const port=(server.address() as {port:number}).port; const allowed=await fetch(`http://127.0.0.1:${port}/api/v1/tasks`,{method:'OPTIONS',headers:{Origin:'http://127.0.0.1:5173','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Authorization, Content-Type, X-Request-Id'}}); assert.equal(allowed.status,204); assert.equal(allowed.headers.get('access-control-allow-origin'),'http://127.0.0.1:5173'); assert.match(allowed.headers.get('x-request-id')??'',/^[0-9a-f-]{36}$/u); assert.match(allowed.headers.get('access-control-expose-headers')??'',/X-Request-Id/u); const denied=await fetch(`http://127.0.0.1:${port}/api/v1/tasks`,{method:'OPTIONS',headers:{Origin:'https://evil.example','Access-Control-Request-Method':'POST'}}); assert.equal(denied.status,403); assert.equal(denied.headers.get('access-control-allow-origin'),null); } finally { server.close(); store.close(); } });
test('request ids are bounded and unexpected failures produce safe correlated logs',async()=>{ const store=new SqliteStore(':memory:'); const entries:import('../src/server.js').OperationalLogEntry[]=[]; const broken=new Proxy(store,{get(target,property){ if(property==='list') return ()=>{ throw new Error('SYNTHETIC_PRIVATE_DETAIL'); }; const value=Reflect.get(target,property) as unknown; return typeof value==='function'?value.bind(target):value; }}); const server=createApiServer(broken,[],entry=>entries.push(entry)); server.listen(0,'127.0.0.1'); await once(server,'listening'); try { const port=(server.address() as {port:number}).port; const token=issueToken(store,'owner',['tasks:read']); const supplied='123e4567-e89b-42d3-a456-426614174000'; const response=await fetch(`http://127.0.0.1:${port}/api/v1/tasks`,{headers:{Authorization:`Bearer ${token}`,'X-Request-Id':supplied}}); assert.equal(response.status,500); assert.equal(response.headers.get('x-request-id'),supplied); assert.deepEqual(entries,[{level:'error',event:'api.request.failed',requestId:supplied,method:'GET',route:'/api/v1/tasks',status:500,errorType:'Error'}]); assert.equal(JSON.stringify(entries).includes('SYNTHETIC_PRIVATE_DETAIL'),false); const replaced=await fetch(`http://127.0.0.1:${port}/api/health`,{headers:{'X-Request-Id':'untrusted value'}}); assert.match(replaced.headers.get('x-request-id')??'',/^[0-9a-f-]{36}$/u); assert.notEqual(replaced.headers.get('x-request-id'),'untrusted value'); } finally { server.close(); store.close(); } });
