// SPDX-FileCopyrightText: 2026 Zendrhax LLC
// SPDX-License-Identifier: MPL-2.0
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { Permission, Principal, Task, TaskRepository, TokenRepository } from './contracts.js';

export class ApiError extends Error { constructor(readonly status:number, readonly code:string, message:string) { super(message); } }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
export function tokenHash(token:string):string { return createHash('sha256').update(token).digest('hex'); }
export async function issueToken(repo:TokenRepository, subject:string, permissions:readonly Permission[], hours=24):Promise<string> { if (!/^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/u.test(subject) || hours<1 || hours>24) throw new ApiError(422,'VALIDATION_FAILED','Invalid token request.'); const token=randomBytes(32).toString('hex'); await repo.issue(tokenHash(token),subject,[...new Set(permissions)].sort(),Math.floor(Date.now()/1000)+hours*3600); return token; }
export async function authenticate(repo:TokenRepository, header:string|undefined):Promise<Principal> { if (!header?.startsWith('Bearer ') || header.length>512) throw new ApiError(401,'UNAUTHENTICATED','Authentication is required.'); const token=header.slice(7); if (!/^[0-9a-f]{64}$/u.test(token)) throw new ApiError(401,'UNAUTHENTICATED','Authentication is required.'); const principal=await repo.authenticate(tokenHash(token),Math.floor(Date.now()/1000)); if (!principal) throw new ApiError(401,'UNAUTHENTICATED','Authentication is required.'); return principal; }
export function requirePermission(principal:Principal, permission:Permission):void { if (!principal.permissions.includes(permission)) throw new ApiError(403,'FORBIDDEN','The operation is not permitted.'); }
export function canonicalId(id:string):string { if (!UUID.test(id)) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); return id; }
export function title(value:unknown):string { if (typeof value!=='string') throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); const clean=value.trim(); if (clean.length<1 || [...clean].length>80 || /[\p{Cc}\p{Cs}\p{Zl}\p{Zp}]/u.test(clean)) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); return clean; }
export async function createTask(repo:TaskRepository, principal:Principal, input:Record<string,unknown>):Promise<Task> { requirePermission(principal,'tasks:write'); exact(input,['title']); const task={id:randomUUID(),title:title(input.title),completed:false,version:1}; await repo.create(principal.subject,task); return task; }
export async function replaceTask(repo:TaskRepository, principal:Principal,id:string,input:Record<string,unknown>):Promise<Task> { requirePermission(principal,'tasks:read'); requirePermission(principal,'tasks:write'); exact(input,['title','completed','version']); if(typeof input.completed!=='boolean'||!Number.isInteger(input.version)||Number(input.version)<1||Number(input.version)>2147483645) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); const task={id:canonicalId(id),title:title(input.title),completed:input.completed,version:Number(input.version)+1}; const result=await repo.replace(principal.subject,task,Number(input.version)); if(result==='missing') throw new ApiError(404,'NOT_FOUND','The resource was not found.'); if(result==='conflict') throw new ApiError(409,'VERSION_CONFLICT','The resource changed; reload it.'); return task; }
export function exact(input:Record<string,unknown>, keys:string[]):void { if(Object.keys(input).sort().join('|')!==[...keys].sort().join('|')) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); }
