// SPDX-FileCopyrightText: 2026 Zendrhax LLC
// SPDX-License-Identifier: MPL-2.0
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { ApiError, authenticate, canonicalId, createTask, exact, replaceTask, requirePermission } from './application.js';
import type { Principal, RateLimitRepository, TaskRepository, TokenRepository } from './contracts.js';
import { SqliteStore } from './sqlite.js';

type Store = TaskRepository & TokenRepository & RateLimitRepository;
export type OperationalLogEntry = Readonly<{level:'error'; event:'api.request.failed'; requestId:string; method:string; route:string; status:number; errorType:string}>;
export type OperationalLogger = (entry:OperationalLogEntry)=>void;
const defaultLogger:OperationalLogger = entry => process.stderr.write(`${JSON.stringify(entry)}\n`);
export function createApiServer(store:Store, allowedOrigins:readonly string[] = [], logger:OperationalLogger = defaultLogger) { const origins=new Set(allowedOrigins); return createServer(async (request,response) => { const requestId=requestIdFor(request); response.setHeader('X-Request-Id',requestId); response.setHeader('Content-Language',locale(request)); response.setHeader('Vary','Accept-Language, Origin'); try { cors(request,response,origins); if(request.method==='OPTIONS') return preflight(request,response,origins); await route(store,request,response); } catch(error) { const status=error instanceof ApiError?error.status:500; if(status>=500) safeLog(logger,{level:'error',event:'api.request.failed',requestId,method:request.method??'GET',route:routeLabel(request.url),status,errorType:error instanceof Error?error.constructor.name:'UnknownError'}); fail(response,error,locale(request)); } }); }

function requestIdFor(request:IncomingMessage):string { const value=Array.isArray(request.headers['x-request-id'])?'':request.headers['x-request-id']??''; return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(value)?value:randomUUID(); }
function routeLabel(raw:string|undefined):string { const path=new URL(raw??'/', 'http://local').pathname; if(path==='/api/health') return '/api/health'; if(/^\/api\/v1\/tasks\/[^/]+$/u.test(path)) return '/api/v1/tasks/{id}'; if(['/api/v1/tasks','/api/v1/auth/session','/api/v1/auth/token'].includes(path)) return path; return 'unmatched'; }
function safeLog(logger:OperationalLogger,entry:OperationalLogEntry):void { try { logger(entry); } catch { /* Logging must not replace the safe API response. */ } }

async function route(store:Store, request:IncomingMessage, response:ServerResponse):Promise<void> {
  const url=new URL(request.url??'/', 'http://local'); const method=request.method??'GET';
  if(url.pathname==='/api/health' && (method==='GET'||method==='HEAD')) return send(response,200,{status:'ok',scope:'liveness'},method==='HEAD');
  if(!url.pathname.startsWith('/api/v1/')) throw new ApiError(404,'NOT_FOUND','The resource was not found.');
  rate(store,request); const principal=authenticate(store, Array.isArray(request.headers.authorization)?undefined:request.headers.authorization);
  if(url.pathname==='/api/v1/auth/session' && method==='GET') return send(response,200,{data:{subject:principal.subject,permissions:principal.permissions}});
  if(url.pathname==='/api/v1/auth/token' && method==='DELETE') { store.revoke(principal.tokenId); response.writeHead(204,securityHeaders()); response.end(); return; }
  if(url.pathname==='/api/v1/tasks') return tasks(store,principal,url,method,request,response);
  const match=/^\/api\/v1\/tasks\/([^/]+)$/u.exec(url.pathname); if(match) { let id:string; try{id=decodeURIComponent(match[1]!);}catch{throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.');} return one(store,principal,canonicalId(id),method,request,response); }
  throw new ApiError(404,'NOT_FOUND','The resource was not found.');
}
async function tasks(store:Store,p:Principal,url:URL,method:string,req:IncomingMessage,res:ServerResponse):Promise<void>{
  if(method==='GET'){ requirePermission(p,'tasks:read'); const raw=url.searchParams.get('limit')??'20'; const keys=[...url.searchParams.keys()]; if(!/^\d+$/u.test(raw)||Number(raw)<1||Number(raw)>100||keys.some(k=>!['limit','after'].includes(k))||new Set(keys).size!==keys.length) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); const after=url.searchParams.get('after')??undefined; if(after) canonicalId(after); return send(res,200,store.list(p.subject,Number(raw),after)); }
  if(method==='POST'){ const task=createTask(store,p,await body(req)); return send(res,201,{data:task},false,{'Location':'/api/v1/tasks/'+task.id}); }
  throw methodError(['GET','POST']);
}
async function one(store:Store,p:Principal,id:string,method:string,req:IncomingMessage,res:ServerResponse):Promise<void>{
  if(method==='GET'){ requirePermission(p,'tasks:read'); const task=store.find(p.subject,id); if(!task) throw new ApiError(404,'NOT_FOUND','The resource was not found.'); return send(res,200,{data:task}); }
  if(method==='PUT'){ return send(res,200,{data:replaceTask(store,p,id,await body(req))}); }
  if(method==='DELETE'){ requirePermission(p,'tasks:read'); requirePermission(p,'tasks:write'); const input=await body(req); exact(input,['version']); if(!Number.isInteger(input.version)||Number(input.version)<1||Number(input.version)>2147483646) throw new ApiError(422,'VALIDATION_FAILED','The request does not satisfy the contract.'); const result=store.remove(p.subject,id,Number(input.version)); if(result==='missing') throw new ApiError(404,'NOT_FOUND','The resource was not found.'); if(result==='conflict') throw new ApiError(409,'VERSION_CONFLICT','The resource changed; reload it.'); res.writeHead(204,securityHeaders()); res.end(); return; }
  throw methodError(['GET','PUT','DELETE']);
}
async function body(request:IncomingMessage):Promise<Record<string,unknown>> { if(request.headers['content-type']?.split(';')[0]?.trim().toLowerCase()!=='application/json') throw new ApiError(415,'UNSUPPORTED_MEDIA_TYPE','Content-Type must be application/json.'); const chunks:Buffer[]=[]; let length=0; for await(const chunk of request){ const bytes=Buffer.from(chunk); length+=bytes.length; if(length>8192) throw new ApiError(413,'PAYLOAD_TOO_LARGE','The request body is too large.'); chunks.push(bytes); } try { const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks))) as unknown; if(!value||typeof value!=='object'||Array.isArray(value)) throw new Error(); return value as Record<string,unknown>; } catch { throw new ApiError(400,'BAD_REQUEST','A valid JSON object is required.'); } }
function methodError(allow:string[]):ApiError { const error=new ApiError(405,'METHOD_NOT_ALLOWED','The method is not allowed.'); Object.assign(error,{allow}); return error; }
function cors(request:IncomingMessage,response:ServerResponse,origins:Set<string>):void { const origin=Array.isArray(request.headers.origin)?'':request.headers.origin; if(origin&&origins.has(origin)) { response.setHeader('Access-Control-Allow-Origin',origin); response.setHeader('Access-Control-Expose-Headers','X-Request-Id, Location'); } }
function preflight(request:IncomingMessage,response:ServerResponse,origins:Set<string>):void { const origin=Array.isArray(request.headers.origin)?'':request.headers.origin; const method=Array.isArray(request.headers['access-control-request-method'])?'':request.headers['access-control-request-method']??''; const requested=Array.isArray(request.headers['access-control-request-headers'])?'':request.headers['access-control-request-headers']??''; const headers=requested.split(',').map(value=>value.trim().toLowerCase()).filter(Boolean); if(!origin||!origins.has(origin)||!['GET','POST','PUT','DELETE'].includes(method.toUpperCase())||headers.some(value=>!['authorization','content-type','accept-language','x-request-id'].includes(value))||!(request.url??'').startsWith('/api/v1/')) throw new ApiError(403,'FORBIDDEN','The operation is not permitted.'); response.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, PUT, DELETE','Access-Control-Allow-Headers':'Authorization, Content-Type, Accept-Language, X-Request-Id','Access-Control-Expose-Headers':'X-Request-Id, Location','Access-Control-Max-Age':'600','Cache-Control':'no-store'}); response.end(); }
function rate(store:Store,request:IncomingMessage):void { const key=createHash('sha256').update(request.socket.remoteAddress??'unknown').digest('hex'); if(!store.consume(key,Math.floor(Date.now()/60000),120)) throw new ApiError(429,'RATE_LIMITED','Too many requests.'); }
function securityHeaders(extra:Record<string,string>={}):Record<string,string>{ return {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}; }
function send(response:ServerResponse,status:number,payload:unknown,head=false,headers:Record<string,string>={}):void { response.writeHead(status,securityHeaders(headers)); response.end(head?'':JSON.stringify(payload)); }
function locale(request:IncomingMessage):'es-419'|'en-US' { const value=Array.isArray(request.headers['accept-language'])?'':request.headers['accept-language']??''; const choices=value.split(',').map((item,index)=>{const [language,...parameters]=item.trim().split(';'); const raw=parameters.find(p=>p.trim().startsWith('q='))?.split('=')[1]; const q=raw===undefined?1:Number(raw); return {language:language??'',q:Number.isFinite(q)&&q>=0&&q<=1?q:0,index};}).filter(item=>item.q>0&&/^(?:es|en)(?:-|$)/iu.test(item.language)).sort((a,b)=>b.q-a.q||a.index-b.index); return choices[0]&&/^es(?:-|$)/iu.test(choices[0].language)?'es-419':'en-US'; }
const spanish:Record<string,string>={UNAUTHENTICATED:'Se requiere autenticación.',FORBIDDEN:'La operación no está permitida.',NOT_FOUND:'No se encontró el recurso.',VALIDATION_FAILED:'Los valores proporcionados no cumplen el contrato.',BAD_REQUEST:'Se requiere un objeto JSON válido.',UNSUPPORTED_MEDIA_TYPE:'Content-Type debe ser application/json.',PAYLOAD_TOO_LARGE:'El cuerpo de la solicitud es demasiado grande.',VERSION_CONFLICT:'El recurso cambió; vuelve a cargarlo.',METHOD_NOT_ALLOWED:'El método no está permitido.',RATE_LIMITED:'Demasiadas solicitudes.',INTERNAL_ERROR:'Ocurrió un error inesperado.'};
function fail(response:ServerResponse,error:unknown,language:'es-419'|'en-US'):void { const known=error instanceof ApiError; const status=known?error.status:500; const code=known?error.code:'INTERNAL_ERROR'; const message=language==='es-419'?(spanish[code]??spanish.INTERNAL_ERROR):known?error.message:'An unexpected error occurred.'; const headers:Record<string,string>={}; if(status===401) headers['WWW-Authenticate']='Bearer'; if(status===429) headers['Retry-After']='60'; const allow=(error as {allow?:string[]})?.allow; if(allow) headers.Allow=allow.join(', '); send(response,status,{error:{code,message}},false,headers); }

if(process.argv[1] && pathToFileURL(resolve(process.argv[1])).href===import.meta.url){ const host=process.env.HOST??'127.0.0.1', port=Number(process.env.PORT??'8081'); if(!['local','testing'].includes(process.env.APP_ENV??'local')) throw new Error('Local HTTP launcher refused outside local/testing. Use reviewed TLS termination.'); const origins=(process.env.API_ALLOWED_ORIGINS??'').split(',').map(value=>value.trim()).filter(Boolean); const store=new SqliteStore(process.env.DB_DATABASE??'database.sqlite'); createApiServer(store,origins).listen(port,host,()=>process.stdout.write(`Local evaluation API listening on http://${host}:${port}\n`)); }
